version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  postmark:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Postmark-cli
          command: |
            npm i postmark-cli -g
      - run:
          name: Push templates to Postmark
          command: |
            postmark templates push ./postmark -f

workflows:
  version: 2
  build_and_postmark:
    jobs:
      - build
      - postmark_approval:
          requires:
            - build
          type: approval
      - postmark:
          requires:
            - postmark_approval
          filters:
              branches:
                only: master

